<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.ochobits</groupId>
    <artifactId>Serenity-Web-Driver</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>21</java.version>

        <serenity.version>5.3.8</serenity.version>
        <seleniumhq.version>4.48.0</seleniumhq.version>
        <junit.version>6.0.3</junit.version> <!-- ULTIMA VERSION 6.1.3 -->
<!--        <spring.version>7.0.8</spring.version>-->
        <lombok.version>1.18.42</lombok.version>
    </properties>

<!--    <dependencyManagement>-->
<!--        <dependencies>-->
<!--            <dependency>-->
<!--                <groupId>org.springframework</groupId>-->
<!--                <artifactId>spring-framework-bom</artifactId>-->
<!--                <version>${spring.version}</version>-->
<!--                <scope>import</scope>-->
<!--                <type>pom</type>-->
<!--            </dependency>-->
<!--        </dependencies>-->
<!--    </dependencyManagement>-->

    <dependencies>
<!--        <dependency>-->
<!--            <groupId>org.springframework</groupId>-->
<!--            <artifactId>spring-core</artifactId>-->
<!--        </dependency>-->

<!--        <dependency>-->
<!--            <groupId>org.springframework</groupId>-->
<!--            <artifactId>spring-context</artifactId>-->
<!--        </dependency>-->

<!--        <dependency>-->
<!--            <groupId>org.springframework</groupId>-->
<!--            <artifactId>spring-tx</artifactId>-->
<!--        </dependency>-->

        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>${seleniumhq.version}</version>
            <scope>test</scope>
        </dependency>

<!--        <dependency>-->
<!--            <groupId>net.serenity-bdd</groupId>-->
<!--            <artifactId>serenity-core</artifactId>-->
<!--            <version>${serenity.version}</version>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>net.serenity-bdd</groupId>-->
<!--            <artifactId>serenity-junit5</artifactId>-->
<!--            <version>${serenity.version}</version>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>net.serenity-bdd</groupId>-->
<!--            <artifactId>serenity-screenplay</artifactId>-->
<!--            <version>${serenity.version}</version>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>net.serenity-bdd</groupId>-->
<!--            <artifactId>serenity-screenplay-webdriver</artifactId>-->
<!--            <version>${serenity.version}</version>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>net.serenity-bdd</groupId>-->
<!--            <artifactId>serenity-ensure</artifactId>-->
<!--            <version>${serenity.version}</version>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>net.serenity-bdd</groupId>-->
<!--            <artifactId>serenity-cucumber</artifactId>-->
<!--            <version>${serenity.version}</version>-->
<!--        </dependency>-->

        <!-- JUNIT 5 DEPENDENCY-->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
<!--        <dependency>-->
<!--            <groupId>org.assertj</groupId>-->
<!--            <artifactId>assertj-core</artifactId>-->
<!--            <version>${assertj.version}</version>-->
<!--            <scope>test</scope>-->
<!--        </dependency>-->

        <!-- Source: https://mvnrepository.com/artifact/org.projectlombok/lombok -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
            <scope>compile</scope>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.15.0</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>

            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity.version}</version>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

        </plugins>
    </build>

</project>